# http://travis-ci.org/#!/jupyter-widgets/ipywidgets
language: python
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
addons:
  apt_packages:
    - pandoc
  firefox: latest
cache: yarn
env:
    - GROUP=python
sudo: false
before_install:
    - 'if [[ $GROUP == python ]] ; then bash ./scripts/travis_before_install_py.sh ; fi'
    - 'if [[ $GROUP == doc ]] ; then bash ./scripts/travis_before_install_py.sh ; fi'
    - 'if [[ $GROUP == spec ]] ; then bash ./scripts/travis_before_install_py.sh ; fi'
install:
    - 'if [[ $GROUP == python ]] ; then bash ./scripts/travis_install_py.sh ; fi'
    - 'if [[ $GROUP == doc ]] ; then bash ./scripts/travis_install_py.sh ; fi'
    - 'if [[ $GROUP == spec ]] ; then bash ./scripts/travis_install_py.sh ; fi'
    - 'if [[ $GROUP == js ]] ; then bash ./scripts/travis_install_js.sh ; fi'
script:
    - 'if [[ $GROUP == python ]] ; then bash ./scripts/travis_script_py.sh ; fi'
    - 'if [[ $GROUP == doc ]] ; then bash ./scripts/travis_script_doc.sh ; fi'
    - 'if [[ $GROUP == spec ]] ; then bash ./scripts/travis_script_spec.sh ; fi'
    - 'if [[ $GROUP == js ]] ; then bash ./scripts/travis_script_js.sh ; fi'
matrix:
    include:
        - python: 3.6
          env: GROUP=spec
        - python: 3.6
          env: GROUP=doc
        - python: 3.6
          env: GROUP=js BROWSER=firefox TRAVIS_NODE_VERSION=6.11.0
after_success:
    - coveralls
