name: ipywidgets_docs
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python >=3.11,<3.12
  # build
  - python-build
  - pip
  - packaging
  - jupyter-packaging
  - jupyterlab >=4,<5
  - nodejs >=18,<19
  # dependencies
  - jupyter_client
  # docs
  - docutils >=0.19
  - jupyterlab-myst
  - myst-nb >=0.17,<0.18
  - pandoc
  - pydata-sphinx-theme
  - sphinx >=5,<6
  - sphinx-autobuild
  - sphinx-autodoc-typehints
  - sphinx-copybutton
  - sphinxext-rediraffe
  # demo
  - bqplot
  - ipykernel
  - ipyleaflet
  - jupyterlite >=0.1.2,<0.2.0
  - jupyterlite-pyodide-kernel >=0.1.2,<0.2.0
  - matplotlib-base
  - numpy
  - scikit-image
  - scikit-learn
  - sympy
