name: ipywidget_docs
channels:
- conda-forge
dependencies:
- python=3.5
- sphinx_rtd_theme
- jinja2
- tornado
- nbformat
- ipywidgets
- notebook>=4.2
- pip:
  - sphinx==1.4.5
  - nbsphinx==0.2.7
  - sphinx_rtd_theme==0.1.10-alpha
  - python-dateutil
