name: docs
channels:
  - conda-forge
  - nodefaults
dependencies:
  - bqplot
  - empack
  - ipykernel
  - jupyter_client
  - jupyterlab >=3,<4
  - jupyter-packaging
  - matplotlib
  - nbsphinx
  - nodejs=14
  - numpy
  - packaging
  - pandoc
  - pip
  - python=3.10
  - recommonmark
  - scikit-image
  - scikit-learn
  - sphinx
  - sphinx_rtd_theme
  - sympy
  - pip:
    - jupyterlite==0.1.0b10
    - jupyterlite-sphinx>=0.6.0
