name: Build jupyterlab_widgets

on:
  push:
    branches: main
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Cache pip on Linux
        uses: actions/cache@v3
        if: startsWith(runner.os, 'Linux')
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python }}

      - name: Install build dependencies
        run: |
          python -m pip install jupyterlab jupyter_packaging~=0.10

      - name: Install node dependencies
        run: |
          jlpm

      - name: Build node packages
        run: |
          jlpm build

      - name: Install jupyterlab_widgets
        run: |
          cd python/jupyterlab_widgets
          pip install -vv -e . --no-deps

      - name: Install widgetsnbextension
        run: |
          cd python/widgetsnbextension
          pip install -vv -e . --no-deps

      - name: Install ipywidgets
        run: |
          cd python/ipywidgets
          pip install -vv . --no-deps

      - name: Install development extension
        run: |
          cd python/jupyterlab_widgets
          jupyter labextension develop . --overwrite

      - name: List labextensions
        run: |
          jupyter labextension list

      - name: Run JupyterLab browser check
        run: |
          python -m jupyterlab.browser_check
